package agent

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/agentjoey/pactify/internal/pact"
)

// briefing renders the agent-agnostic onboarding body (MCP-first, shell fallback).
func briefing(seatID, roles string) string {
	return fmt.Sprintf(`# pact protocol — seat `+"`%s`"+`

This repo uses the **pact protocol** (v1). You are seat `+"`%s`"+`, roles: %s.

**Primary — MCP:** the `+"`pact`"+` MCP server is wired into your config. Use its tools
(status / join / assign / checkpoint / accept / changes / merge / list) and resources
(`+"`pact://state`"+`, `+"`pact://log`"+`). Cold start: call `+"`status`"+`, then `+"`join`"+`
(registers your seat and checks out your feature branch).

**Fallback — shell** (if MCP is unavailable):
`+"```bash"+`
export PACT_AGENT_ID=%s
pactify join %s --roles %s
`+"```"+`
then `+"`pactify help`"+` for the verbs.

**The two rules:** a worker cannot self-accept (only the task's reviewer accepts); a
feature cannot merge until all its tasks are accepted.`, seatID, seatID, roles, seatID, seatID, roles)
}

// Render returns the entry-file block (empty if the kind has no entry file) and
// the config snippet for a kind. Pure: no IO.
func Render(kind, seatID, roles, repoAbs string) (entry, config string, err error) {
	a, ok := Get(kind)
	if !ok {
		return "", "", fmt.Errorf("unknown agent kind %q (supported: %v)", kind, Kinds())
	}
	if a.DefaultEntry() != "" {
		entry = briefing(seatID, roles)
	}
	config = snippet(a.Config().Format, a.Invocation(seatID, repoAbs))
	return entry, config, nil
}

// RenderDoc renders the manual-onboarding reference for every kind. The output
// is committed as docs/agent-onboarding.md and a test asserts it stays in sync.
func RenderDoc() string {
	var b strings.Builder
	b.WriteString("# Agent onboarding (manual reference)\n\n")
	b.WriteString("Generated by `pactify agent docs`. For each kind, `pactify agent add <kind> --id <seat> --roles <roles>` does this for you.\n\n")
	for _, k := range Kinds() {
		a, _ := Get(k)
		c := a.Config()
		entry, cfg, _ := Render(k, "SEAT_ID", "ROLES", "REPO_DIR")
		fmt.Fprintf(&b, "## %s\n\n", k)
		fmt.Fprintf(&b, "- config: `%s` (%s)\n", c.Path, scopeName(c.Scope))
		if a.DefaultEntry() != "" {
			fmt.Fprintf(&b, "- entry file: `%s`\n\n", a.DefaultEntry())
			fmt.Fprintf(&b, "Entry block:\n\n````markdown\n%s\n````\n\n", entry)
		} else {
			b.WriteString("- entry file: none (desktop app)\n\n")
		}
		fmt.Fprintf(&b, "Config:\n\n```\n%s```\n\n", cfg)
	}
	return b.String()
}

func scopeName(s Scope) string {
	if s == Global {
		return "machine-global"
	}
	return "project, committed in repo"
}

// Wire performs the onboarding side effects for kind rooted at the current
// working directory (the CLI runs from the repo root). It is WireAt(".", …).
func Wire(kind, seatID, roles, repoAbs string) error {
	return WireAt(".", kind, seatID, roles, repoAbs)
}

// WireAt performs the onboarding side effects for kind, rooting project-scoped
// writes at dir (so a caller need not chdir): bake the entry block (if the kind
// has an entry file) and, for JSON kinds, merge the pact server into the agent's
// config. TOML kinds are doc-only — their config is not written (the caller
// prints the snippet). Global-scoped configs are written at their machine path
// (ExpandPath) regardless of dir; only project-relative paths are joined to dir.
// repoAbs is the repo path baked into the agent invocation (env/args).
func WireAt(dir, kind, seatID, roles, repoAbs string) error {
	a, ok := Get(kind)
	if !ok {
		return fmt.Errorf("unknown agent kind %q (supported: %v)", kind, Kinds())
	}
	if a.DefaultEntry() != "" {
		if err := pact.BakeManagedBlock(filepath.Join(dir, a.DefaultEntry()), briefing(seatID, roles)); err != nil {
			return err
		}
	}
	c := a.Config()
	if c.Format == TOML {
		return nil // doc-only
	}
	cfgPath := ExpandPath(c.Path)
	if c.Scope == Project {
		cfgPath = filepath.Join(dir, c.Path)
	}
	return mergeServer(cfgPath, c.Format, a.Invocation(seatID, repoAbs))
}
