package agent

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/agentjoey/pactify/internal/pact"
)

// briefing renders the SEAT-AGNOSTIC onboarding body (MCP-first, shell fallback).
// It names no seat: identity is a working-copy/session property resolved at
// runtime (env PACT_AGENT_ID > the .pact/seat file — spec seat-identity), not a
// per-repo shared-file property. This makes the block byte-identical for every
// seat, so wiring N seats of the same kind into one repo is idempotent instead
// of last-writer-wins (the 2026-07-22 collision). The roster lives in
// .pact/PROJECT.md / STATE.yml.
func briefing() string {
	return `# pact protocol

This repo uses the **pact protocol** (v1). Seats (who does what) are listed in
` + "`.pact/PROJECT.md`" + ` and ` + "`.pact/STATE.yml`" + `.

**Your identity — bind it to this working copy first.** Your seat is resolved
from ` + "`PACT_AGENT_ID`" + ` (env), else the untracked ` + "`.pact/seat`" + ` file. Set the
file once per working copy:
` + "```bash" + `
pactify seat use <your-seat-id>   # from the roster in .pact/PROJECT.md
` + "```" + `
For concurrent seats in the same repo, use a separate git worktree per seat.

**Primary — MCP:** the ` + "`pact`" + ` MCP server is wired into your config. Use its tools
(projects / status / join / assign / checkpoint / accept / changes / merge / validate) and
resources (` + "`pact://state`" + `, ` + "`pact://log`" + `). Cold start: call ` + "`status`" + `, then ` + "`join`" + `
(registers your seat and checks out your feature branch). Every action tool takes an
optional ` + "`project`" + ` (a name from ` + "`projects`" + `) to act on another registered repo without
restarting — default is this repo.

**Fallback — shell** (if MCP is unavailable):
` + "```bash" + `
pactify seat use <your-seat-id>   # if not already bound
pactify join --roles <your-roles>
` + "```" + `
then ` + "`pactify help`" + ` for the verbs.

**The two rules:** a worker cannot self-accept (only the task's reviewer accepts); a
feature cannot merge until all its tasks are accepted.`
}

// Render returns the entry-file block (empty if the kind has no entry file) and
// the config snippet for a kind. Pure: no IO.
func Render(kind, seatID, roles, repoAbs string) (entry, config string, err error) {
	a, ok := Get(kind)
	if !ok {
		return "", "", fmt.Errorf("unknown agent kind %q (supported: %v)", kind, Kinds())
	}
	if a.DefaultEntry() != "" {
		// The rendered block carries the kind attribution WireAt would bake, so a
		// hand-pasted block is probed exactly like a wired one (entrymark.go).
		entry = entryBody([]string{kind})
	}
	config = snippet(a.Config().Format, a.Invocation(seatID, repoAbs))
	return entry, config, nil
}

// RenderDoc renders the manual-onboarding reference for every kind. The output
// is committed as docs/agent-onboarding.md and a test asserts it stays in sync.
func RenderDoc() string {
	var b strings.Builder
	b.WriteString("# Agent onboarding (manual reference)\n\n")
	b.WriteString("Generated by `pactify agent docs`. For each kind, `pactify agent add <kind> --id <seat> --roles <roles>` does this for you.\n\n")
	for _, k := range Kinds() {
		a, _ := Get(k)
		c := a.Config()
		entry, cfg, _ := Render(k, "SEAT_ID", "ROLES", "REPO_DIR")
		fmt.Fprintf(&b, "## %s\n\n", k)
		fmt.Fprintf(&b, "- config: `%s` (%s)\n", c.Path, scopeName(c.Scope))
		if a.DefaultEntry() != "" {
			fmt.Fprintf(&b, "- entry file: `%s`\n\n", a.DefaultEntry())
			fmt.Fprintf(&b, "Entry block:\n\n````markdown\n%s\n````\n\n", entry)
		} else {
			b.WriteString("- entry file: none (desktop app)\n\n")
		}
		fmt.Fprintf(&b, "Config:\n\n```\n%s```\n\n", cfg)
	}
	return b.String()
}

func scopeName(s Scope) string {
	if s == Global {
		return "machine-global"
	}
	return "project, committed in repo"
}

// Wire performs the onboarding side effects for kind rooted at the current
// working directory (the CLI runs from the repo root). It is WireAt(".", …).
func Wire(kind, seatID, roles, repoAbs string) error {
	return WireAt(".", kind, seatID, roles, repoAbs)
}

// WireAt performs the onboarding side effects for kind, rooting project-scoped
// writes at dir (so a caller need not chdir): bake the entry block (if the kind
// has an entry file) and, for JSON kinds, merge the pact server into the agent's
// config. TOML kinds are doc-only — their config is not written (the caller
// prints the snippet). Global-scoped configs are written at their machine path
// (ExpandPath) regardless of dir; only project-relative paths are joined to dir.
// repoAbs is the repo path baked into the agent invocation (env/args).
func WireAt(dir, kind, seatID, roles, repoAbs string) error {
	a, ok := Get(kind)
	if !ok {
		return fmt.Errorf("unknown agent kind %q (supported: %v)", kind, Kinds())
	}
	if entry := a.DefaultEntry(); entry != "" {
		// Bake the briefing plus the kind attribution, UNIONed with whatever the
		// block already claimed: entry files are shared (AGENTS.md by five kinds),
		// so wiring a second kind must add to the claim, not replace it. A block
		// with no attribution line (baked by an older pactify) carries no claim to
		// preserve — it is replaced by this kind's, which is the only wiring this
		// run can actually vouch for (entrymark.go).
		p := filepath.Join(dir, entry)
		kinds := []string{kind}
		if b, err := os.ReadFile(p); err == nil {
			if existing, attributed := entryKinds(string(b)); attributed {
				kinds = mergeEntryKinds(existing, kind)
			}
		}
		if err := pact.BakeManagedBlock(p, entryBody(kinds)); err != nil {
			return err
		}
	}
	c := a.Config()
	if c.Format == TOML {
		return nil // doc-only
	}
	cfgPath := ExpandPath(c.Path)
	if c.Scope == Project {
		cfgPath = filepath.Join(dir, c.Path)
	}
	return mergeServer(cfgPath, c.Format, a.Invocation(seatID, repoAbs))
}
